name = "fractal-metascience"
main = "worker.js"
compatibility_date = "2026-02-01"
account_id = "c6b63a2d52d28f1d47ba7c63e4a00d9e"

[env.production]
route = "api.terra.fractal-metascience.org/*"

[vars]
TERRA_VERSION = "4.2"
ARCHITECT = "Abdurashid Abdukarimov"
ORCID = "0009-0000-6394-4912"
EMAIL = "a.abdukarimov@fractal-metascience.org"
DID = "aiuz:did:aiuz:stakeholder:abdukarimov_aaahash1234567890"
