name: SOVEREIGN_DEPLOY
on: [workflow_dispatch, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Status
        run: echo "FMP Sovereign Core Online"